
package com.github.bruce_mig.loan_eligibility_soap_ws_client.loan_eligibility;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LoanEligibilityIndicatorEndpointService", targetNamespace = "http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility", wsdlLocation = "http://localhost:8080/ws/loanEligibility.wsdl")
public class LoanEligibilityIndicatorEndpointService
    extends Service
{

    private static final URL LOANELIGIBILITYINDICATORENDPOINTSERVICE_WSDL_LOCATION;
    private static final WebServiceException LOANELIGIBILITYINDICATORENDPOINTSERVICE_EXCEPTION;
    private static final QName LOANELIGIBILITYINDICATORENDPOINTSERVICE_QNAME = new QName("http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility", "LoanEligibilityIndicatorEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/loanEligibility.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOANELIGIBILITYINDICATORENDPOINTSERVICE_WSDL_LOCATION = url;
        LOANELIGIBILITYINDICATORENDPOINTSERVICE_EXCEPTION = e;
    }

    public LoanEligibilityIndicatorEndpointService() {
        super(__getWsdlLocation(), LOANELIGIBILITYINDICATORENDPOINTSERVICE_QNAME);
    }

    public LoanEligibilityIndicatorEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOANELIGIBILITYINDICATORENDPOINTSERVICE_QNAME, features);
    }

    public LoanEligibilityIndicatorEndpointService(URL wsdlLocation) {
        super(wsdlLocation, LOANELIGIBILITYINDICATORENDPOINTSERVICE_QNAME);
    }

    public LoanEligibilityIndicatorEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOANELIGIBILITYINDICATORENDPOINTSERVICE_QNAME, features);
    }

    public LoanEligibilityIndicatorEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanEligibilityIndicatorEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoanEligibilityIndicatorEndpoint
     */
    @WebEndpoint(name = "LoanEligibilityIndicatorEndpointSoap11")
    public LoanEligibilityIndicatorEndpoint getLoanEligibilityIndicatorEndpointSoap11() {
        return super.getPort(new QName("http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility", "LoanEligibilityIndicatorEndpointSoap11"), LoanEligibilityIndicatorEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanEligibilityIndicatorEndpoint
     */
    @WebEndpoint(name = "LoanEligibilityIndicatorEndpointSoap11")
    public LoanEligibilityIndicatorEndpoint getLoanEligibilityIndicatorEndpointSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility", "LoanEligibilityIndicatorEndpointSoap11"), LoanEligibilityIndicatorEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOANELIGIBILITYINDICATORENDPOINTSERVICE_EXCEPTION!= null) {
            throw LOANELIGIBILITYINDICATORENDPOINTSERVICE_EXCEPTION;
        }
        return LOANELIGIBILITYINDICATORENDPOINTSERVICE_WSDL_LOCATION;
    }

}
