
package com.github.bruce_mig.loan_eligibility_soap_ws_client.loan_eligibility;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LoanEligibilityIndicatorEndpoint", targetNamespace = "http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanEligibilityIndicatorEndpoint {


    /**
     * 
     * @param customerRequest
     */
    @WebMethod(operationName = "Customer")
    @Oneway
    public void customer(
        @WebParam(name = "CustomerRequest", targetNamespace = "http://www.github.com/bruce_mig/spring_boot_soap_ws/loan_ligibility", partName = "CustomerRequest")
        CustomerRequest customerRequest);

}
